### PR TITLE
Documentation for info-hash change behavior

### PR DESCRIPTION
**Pull request by josecelano**
If you upload a torrent with custom fields in the `info` key dictionary, the torrent infohash changes because we do not parse/store custom fields.

- [x] Add test
- [x] Add ADR
- [x] Store original info-hash in the database (`torrust_torrents` table)
- [ ] ~~Show a warning to the user after uploading the torrent if the info-hash changes~~. ([frontend task](https://github.com/torrust/torrust-index-frontend/issues/242)).

### CODE REVIEW

**Comment by da2ce7** [comment]
Do you think that we should detect that we are removing data from the torrent info-dictionary, and provide a warning when uploading the torrent?

Just silently dropping these fields doesn't seem so nice...

**Comment by josecelano** [comment]
> Do you think that we should detect that we are removing data from the torrent info-dictionary, and provide a warning when uploading the torrent?
> 
> Just silently dropping these fields doesn't seem so nice...

Yes, I think that would be the best solution. For the time being, I was planning just to "statically" inform the user about this behavior. I thought that was what [you proposed](https://github.com/torrust/torrust-index-backend/issues/256#issuecomment-1686562085).

If we want to "dynamically" warn the user when this happens, we have at least two options:

### Option 1

- Parse the uploaded torrent and calculate the right infohash with bip_bencode. I do not know if you want to use the public crate or the [forked version](https://github.com/torrust/torrust-tracker/tree/develop/contrib/bencode) we have on the tracker. If we use our version, we have to publish it.
- Change the upload torrent endpoint response, to include an extra message.

### Option 2

This option requires a more complex UX. When you upload a torrent and the infohash changes, we do not save it. We only save a "draft indexed torrent". Then, we show the user a confirmation message that actually stores the torrent.

I think the UI is not ready for this kind of interaction. It probably requires introducing more UI elements.

### Option 3

We add a static message in the upload form: "The info-hash, might change if you use custom fields.", linking to the User's Guide.

**Comment by da2ce7** [comment]
I think that the best option is to store the original info-hash alongside the original filename in the database.

The uploading torrent endpoint should provide a warning "the infohash has changed from X to Y, as we have removed non-standard keys from the info-dictionary."  This should be displayed to the user after the successful upload.

**Comment by josecelano** [comment]
> I think that the best option is to store the original info-hash alongside the original filename in the database.
> 
> The uploading torrent endpoint should provide a warning "the infohash has changed from X to Y, as we have removed non-standard keys from the info-dictionary." This should be displayed to the user after the successful upload.

OK @da2ce7. I will use the public [bip_encode](https://crates.io/crates/bip_bencode) to get the original infohash.

**Comment by josecelano** [comment]
Hi @da2ce7, I've been thinking about changing the infohash again, and I do not like the side effect. It has a similar effect to the "source" file. As we change the infohash:

- All the trackers listed on the torrent file are not going to work because the infohash has changed.
- Peer can only download the torrent from other peers using the same tracker.

What we are doing is kind of creating a new "normalized" torrent but somehow splitting the swarm.

In a public index/tracker, I think we should generate the same torrent, only adding the linked/associated tracker in the announce list.

**Review by da2ce7 — APPROVED** [review]
ACK 9bb85780f6ee3a978ac1a4c6d54bd88ab623f3fc

**Comment by josecelano** [comment]
> Hi @da2ce7, I've been thinking about changing the infohash again, and I do not like the side effect. It has a similar effect to the "source" file. As we change the infohash:
> 
> * All the trackers listed on the torrent file are not going to work because the infohash has changed.
> * Peer can only download the torrent from other peers using the same tracker.
> 
> What we are doing is kind of creating a new "normalized" torrent but somehow splitting the swarm.
> 
> In a public index/tracker, I think we should generate the same torrent, only adding the linked/associated tracker in the announce list.

Hi @da2ce7 I will merge this PR, but what do you think about this ☝🏼?

**Pull request merged**
