### PR TITLE
Overhaul Testing Workflow

### PR DESCRIPTION
**Pull request by da2ce7**
Rework Testing Workflow

### CODE REVIEW

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK 8eebde9563d9e6f44ee0a945a21540abe33b0820

**Comment by da2ce7** [comment]
Coverage Upload Fail is probably related to a throttling issue.

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK 28013a10419fe5fedf4c5ed17806a9af06d26ef6

**Comment by da2ce7** [comment]
ACK 354cb7d8c5748130afed20ca8dce833c5e9e9934

**Pull request merged**
