### PR TITLE
User authentication should be done in middleware

### LINKED ISSUE #39: User authentication should be done in middleware
User authentication is currently done manually in each endpoint that requires authentication. Ideally, we would have an authentication middleware instead. The authentication middleware could pass `Option<User>` to the endpoint handler.

### PR DESCRIPTION
**Pull request by mario-nt**
Resolves #39.

### CODE REVIEW

**Comment by mario-nt** [comment]
@josecelano Could you please review the final refactor of the extractor and the upload torrent handler before I continue with the remaining handlers?

**Review by josecelano — COMMENTED** [review]
Hi @mario-nt it looks good to me. I've just added some comments regarding the other extractor when the logged-in user is optional.

See https://github.com/torrust/torrust-index/issues/39#issuecomment-1910668709

**Comment by mario-nt** [comment]
Moved

**Comment by mario-nt** [comment]
Parent issue #39 has been split into three new issues with their own PRs. Closing this PR.

**Pull request closed without merging**
