### PR TITLE
#262: Add tower-http compression middleware

### PR DESCRIPTION
**Pull request by alexohneander**
**Modified:**
I have added the tower-http compression to the router.
One test fails, but this did not work before my changes.

### CODE REVIEW

**Comment by josecelano** [comment]
ACK bf3f66f6d2c920bf2f47e03d2a6bee96ef124726

**Comment by josecelano** [comment]
> **Modified:** I have added the tower-http compression to the router. One test fails, but this did not work before my changes.

Hi @alexohneander thank you! I do not see any failing test.

**Comment by alexohneander** [comment]
@josecelano 
I have locally the following Failure:
```bash
failures:
    e2e::web::api::v1::contexts::torrent::contract::for_authenticated_users::it_should_not_allow_uploading_a_torrent_with_a_non_existing_category
```

**Comment by josecelano** [comment]
> @josecelano I have locally the following Failure:
> 
> ```shell
> failures:
>     e2e::web::api::v1::contexts::torrent::contract::for_authenticated_users::it_should_not_allow_uploading_a_torrent_with_a_non_existing_category
> ```

Hi @alexohneander, I'm going to merge the PR because ti seems to work, but I would like to know why it's not working for you. You can run the test with:

```s
cargo test it_should_not_allow_uploading_a_torrent_with_a_non_existing_category -- --nocapture
```

And it should show more info.

**Comment by josecelano** [comment]
And @alexohneander, we use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). The commit message could be something like:

```
feat: [#263] add compression to HTTP responses
```

**Pull request merged**
